"""upgrade enum

Revision ID: 15fe268f62e9
Revises: f77378f19d53
Create Date: 2023-12-23 23:28:40.441016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15fe268f62e9'
down_revision: Union[str, None] = 'f77378f19d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_constraint('category_name_key', 'category', type_='unique')
    op.create_unique_constraint(None, 'check', ['id'])
    op.add_column('group', sa.Column('status', postgresql.ENUM('local', 'globals', name='group_status'), nullable=True))
    op.drop_constraint('shop_name_key', 'shop', type_='unique')
    op.create_unique_constraint(None, 'target', ['id'])
    op.create_unique_constraint(None, 'user_account', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_constraint(None, 'target', type_='unique')
    op.create_unique_constraint('shop_name_key', 'shop', ['name'])
    op.drop_column('group', 'status')
    op.drop_constraint(None, 'check', type_='unique')
    op.create_unique_constraint('category_name_key', 'category', ['name'])
    op.create_table('account',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pwhash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('real_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('home_phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='account_pkey')
    )
    # ### end Alembic commands ###
